[env]
bin = "./zig-out/bin/oops"

[project]
name = "oops"
version = "0.0.1"

[tasks]
test.script = [
    "zig build",
    "rm -rf .oops",
    "%{env.bin} init",
    "%{env.bin} add src",
    "%{env.bin} commit 'initial commit'",
    "%{env.bin} log",
]
